version: "2.24.6"
services:
  flask_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=database
      - DB_NAME=${DB_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  networks:
    backend:

